### ISSUE TITLE
[BUG] Mixin Conflict on Modloader 0.12.5

### ISSUE THREAD

**Issue by itsdinkd** [How-Bout-No/Outvoted#105]
Conflicting with carpet addon mod, Carpet Fixes. Due to this, These two mods (outvoted and carpet fixes) prevent server from starting up. It worked fine on 0.11.7, however not on 0.12.5. 

The dev for Carpet Fixes said to stop using @Override as there is nothing he can do on his end

![image](https://user-images.githubusercontent.com/35115304/142090798-11ed28e7-1f53-4bb7-984a-e9d3abb26941.png)

[21:11:41] [main/ERROR]: Mixin apply for mod carpet-fixes failed carpet-fixes.mixins.json:backports.LightningRodBlock_PermanentlyPoweredMixin -> net.minecraft.class_5554: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_5554::onBlockAdded with priority 1000 cannot inject into net/minecraft/class_5554::method_9615(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Z)V merged by io.github.how_bout_no.outvoted.mixin.MixinLightningRodBlock with priority 1000 [PREINJECT Applicator Phase -> carpet-fixes.mixins.json:backports.LightningRodBlock_PermanentlyPoweredMixin -> Prepare Injections ->  -> handler$che000$onBlockAdded(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_5554::onBlockAdded with priority 1000 cannot inject into net/minecraft/class_5554::method_9615(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Z)V merged by io.github.how_bout_no.outvoted.mixin.MixinLightningRodBlock with priority 1000 [PREINJECT Applicator Phase -> carpet-fixes.mixins.json:backports.LightningRodBlock_PermanentlyPoweredMixin -> Prepare Injections ->  -> handler$che000$onBlockAdded(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
        at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.52) ~[?:?]
        at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at net.minecraft.world.gen.surfacebuilder.SurfaceBuilder.<clinit>(SurfaceBuilder:13) ~[?:?]
        at net.minecraft.world.gen.surfacebuilder.ConfiguredSurfaceBuilders.<clinit>(ConfiguredSurfaceBuilders:11) ~[?:?]
        at net.minecraft.util.registry.BuiltinRegistries.method_30573(BuiltinRegistries:44) ~[?:?]
        at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:75) ~[?:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:723) ~[?:?]
        at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:74) ~[?:?]
        at net.minecraft.util.registry.Registry.<clinit>(Registry:266) ~[?:?]
        at net.minecraft.Bootstrap.initialize(Bootstrap:44) ~[?:?]
        at net.minecraft.server.Main.main(Main:92) [intermediary-server.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:72) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:98) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:60) [fabric-server-launch.jar:?]
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:62)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:100)
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:60)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:74)
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:98)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:72)
        ... 2 more
Caused by: java.lang.RuntimeException: Minecraft has crashed
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:571)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
        ... 7 more
Caused by: java.lang.ExceptionInInitializerError
        at net.minecraft.class_5471.<clinit>(class_5471.java:11)
        at net.minecraft.class_5458.method_30573(class_5458.java:44)
        at net.minecraft.class_5458.method_30566(class_5458.java:75)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:723)
        at net.minecraft.class_5458.<clinit>(class_5458.java:74)
        at net.minecraft.class_2378.<clinit>(class_2378.java:266)
        at net.minecraft.class_2966.method_12851(class_2966.java:44)
        at net.minecraft.server.Main.main(Main.java:92)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
        ... 9 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5554 failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:224)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133)
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        at net.minecraft.class_3523.<clinit>(class_3523.java:13)
        ... 22 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222)
        ... 26 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [carpet-fixes.mixins.json:backports.LightningRodBlock_PermanentlyPoweredMixin] from phase [DEFAULT] in config [carpet-fixes.mixins.json] from mod [carpet-fixes] FAILED during APPLY
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
        ... 29 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_5554::onBlockAdded with priority 1000 cannot inject into net/minecraft/class_5554::method_9615(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Z)V merged by io.github.how_bout_no.outvoted.mixin.MixinLightningRodBlock with priority 1000 [PREINJECT Applicator Phase -> carpet-fixes.mixins.json:backports.LightningRodBlock_PermanentlyPoweredMixin -> Prepare Injections ->  -> handler$che000$onBlockAdded(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
        at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.52)
        at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
        at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133)
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        at net.minecraft.world.gen.surfacebuilder.SurfaceBuilder.<clinit>(SurfaceBuilder:13)
        at net.minecraft.world.gen.surfacebuilder.ConfiguredSurfaceBuilders.<clinit>(ConfiguredSurfaceBuilders:11)
        at net.minecraft.util.registry.BuiltinRegistries.method_30573(BuiltinRegistries:44)
        at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:75)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:723)
        at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:74)
        at net.minecraft.util.registry.Registry.<clinit>(Registry:266)
        at net.minecraft.Bootstrap.initialize(Bootstrap:44)
        at net.minecraft.server.Main.main(Main:92)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:567)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:567)
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:72)
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:98)

**Comment by How-Bout-No** [comment]
Oh ok if it's just the method override causing issues that's a simple fix. It is probably better practice on my part to not override anything I don't need to in mixins.

**Comment by How-Bout-No** [comment]
Should be fixed in beta 4
