### ISSUE TITLE
[BUG] Random crash

### ISSUE THREAD

**Issue by AlisterGontineac** [How-Bout-No/Outvoted#112]
/Before submitting, please ensure you've done the following, as these are fixes for some common bugs:

**Describe the bug**
Crash, think something to do with the glare

**To Reproduce**
not sure

**Screensho
[Crashy Outvoted log.txt](https://github.com/How-Bout-No/Outvoted/files/7690946/Crashy.Outvoted.log.txt)
ts/Logs**

**Version (please complete the following information):**
 - Minecraft Version 1.17.1
 - Modloader Fabric
 - Mod Version outvoted-1.5.0-rc.1

**Additional context**
None, not sure what happened but "Crashy" gave me a rundown

**Comment by How-Bout-No** [comment]
Hm... this is weird. Were you doing anything to/with a Glare in-game?

**Comment by How-Bout-No** [comment]
Looking at the crash report it seems as the Glare that caused the crash for whatever reason is holding Glow Ink Sacs and is trying to place them down... dk why or how it picked them up in the first place

**Comment by AlisterGontineac** [comment]
No, that's really odd. 
I was in a mountain base. Glare naturally spawned in, and as far as I can remember, I didn't use or drop down ink glow sacks. 
Does that mean I can't drop anything without a glare trying to pick it up and crash?

Is the ability to pick things up an unintended bug brought on by another mod possibly? So weird.

**Comment by How-Bout-No** [comment]
It seems I just didn't apply the item filter to picking up items passively, only for the Glare to actively try and pick them up. Meaning that the Glare would pick up any item it happened to run into; so in this case a glow squid must've died and the Glare happened to coast thru its death spot.

Will be fixed next release.

**Comment by AlisterGontineac** [comment]
Ha ha, well that's wild. Thank you very much, I love using this mod!

**Comment by tariqk** [comment]
Hey, not sure if this is related, but I was minding my own business on my base when Minecraft randomly crashed. Same mob, but different error message, linked [here](https://gist.github.com/tariqk/bd25a92837daf60be5d35e90392ff302).

I'm running this on Minecraft 1.17.1, running the Fabric modloader, with Outvoted's version being `outvoted-1.5.0-rc.1`.

Is crash referring to the same problem, or should I raise another issue ticket?

**Comment by Zegveld** [comment]
I've had the same issue as @tariqk and tested it with the latest build. (repo checkout and build locally)
Seems to be fixed, so next release will not have this crash.

**Comment by zedoax** [comment]
Is there a timeline on release of this new version?  I host a server for a lot of my friends to play on and this glitch has caused several of us to be unable to play.  And is there a workaround in the meantime?

**Comment by sanegaming** [comment]
This error is still occurring for me as well:

`[04:14:35] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:895) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:335) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.class_1776 cannot be cast to class net.minecraft.class_1747 (net.minecraft.class_1776 and net.minecraft.class_1747 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @6a5fc7f7)
        at io.github.how_bout_no.outvoted.entity.GlareEntity$InDarkGoal.method_6268(GlareEntity.java:421) ~[outvoted-1.5.0-rc.1.jar:?]
        at net.minecraft.class_4135.method_6268(class_4135.java:55) ~[server-intermediary.jar:?]
        at net.minecraft.class_1355.tickGoals(class_1355.java:1657) ~[server-intermediary.jar:?]
        at net.minecraft.class_1355.method_6275(class_1355.java:1556) ~[server-intermediary.jar:?]
        at net.minecraft.class_1308.method_6023(class_1308.java:733) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_6007(class_1309.java:2601) ~[server-intermediary.jar:?]
        at net.minecraft.class_1308.method_6007(class_1308.java:539) ~[server-intermediary.jar:?]
        at io.github.how_bout_no.outvoted.entity.GlareEntity.method_6007(GlareEntity.java:206) ~[outvoted-1.5.0-rc.1.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2346) ~[server-intermediary.jar:?]
        at net.minecraft.class_1308.method_5773(class_1308.java:339) ~[server-intermediary.jar:?]
        at io.github.how_bout_no.outvoted.entity.GlareEntity.method_5773(GlareEntity.java:200) ~[outvoted-1.5.0-rc.1.jar:?]
        at net.minecraft.class_3218.method_18762(class_3218.java:655) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_18472(class_1937.java:483) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_31420(class_3218.java:417) ~[server-intermediary.jar:?]
        at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18765(class_3218.java:392) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891) ~[server-intermediary.jar:?]
        ... 5 more
[04:14:35] [Server thread/ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2022-04-06_04.14.35-server.txt`

**Comment by othello777** [comment]
We also have this crash. for now we just run `kill @e[type=outvoted:glare]` regularly and that keeps the server from crashing mostly
