### ISSUE TITLE
[BUG][FABRIC] NullPointerException: Cannot read field "wildfireVariants" because "~Outvoted.clientConfig" is null

### ISSUE THREAD

**Issue by dandin87** [How-Bout-No/Outvoted#59]
**Describe the bug**
java.lang.NullPointerException: Cannot read field "wildfireVariants" because "io.github.how_bout_no.outvoted.Outvoted.clientConfig" is null

**Screenshots/Logs**
If applicable, add screenshots to help explain your problem, or logs from Pastebin or similar.
AllOfFabric 4 0.0.8, TeamAOF Public Server
Yarn Mapped Crash Report
https://paste.alloffabric.com/kufowapazi.yaml

**Version (please complete the following information):**
 - Minecraft Version [e.g. 1.16.4 or 1.15.2]
 - 1.17.1
 - Mod Version [e.g. b0.4.0]
2.0.0 Alpha9
**Additional context**

**Comment by How-Bout-No** [comment]
Hm I guess some client call is happening where it should not be. Will be fixed.

**Comment by dandin87** [comment]
Might be related to this similar crash, which Crafty Crashers( https://github.com/Chocohead/Crafty-Crashes managed ) to identify this time.
java.lang.reflect.UndeclaredThrowableException
	at jdk.proxy3/jdk.proxy3.$Proxy93.hurt(Unknown Source)
	at net.minecraft.entity.player.PlayerEntity.handler$zdc001$hurt(dev/architectury/mixin/fabric/PlayerAttackInvoker.java [architectury.mixins.json]:37)
	Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.entity.Entity.setOnFireFor(int)" because the return value of "net.minecraft.entity.damage.DamageSource.getAttacker()" is null
	at io.github.how_bout_no.outvoted.util.EventRegister.lambda$init$2(EventRegister.java:59)
	
https://paste.alloffabric.com/koqomozoju.yaml

**Comment by How-Bout-No** [comment]
This should be fixed in Alpha 10.
