### ISSUE TITLE
[BUG] outvoted fabric with new geckolib crash

### ISSUE THREAD

**Issue by NantaArthur** [How-Bout-No/Outvoted#90]
/Before submitting, please ensure you've done the following, as these are fixes for some common bugs:
[ ] Reset/delete config files
[ ] Run without mods like Optifine (if needed)
[ ] <ins>Double check that you have the latest version!!</ins>

**Describe the bug**
I think your mod have some conflict with the new gecko lib 3.0.16

**To Reproduce**
1. Update Gecko lib and Fabric
2. Crash

**Screenshots/Logs**
```
[11:41:58] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'outvoted'!
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) ~[fabric-server-launch.jar:?]
        at net.minecraft.server.Main.main(Main.java:97) [intermediary-server.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
Caused by: java.lang.NoClassDefFoundError: software/bernie/geckolib3/item/GeoArmorItem
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:170) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at io.github.how_bout_no.outvoted.init.ModItems.<clinit>(ModItems.java:29) ~[outvoted-2.0.0-alpha.13-fabric.jar:?]
        at io.github.how_bout_no.outvoted.Outvoted.init(Outvoted.java:56) ~[outvoted-2.0.0-alpha.13-fabric.jar:?]
        at io.github.how_bout_no.outvoted.OutvotedFabric.onInitialize(OutvotedFabric.java:18) ~[outvoted-2.0.0-alpha.13-fabric.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
        ... 17 more
Caused by: java.lang.ClassNotFoundException: software.bernie.geckolib3.item.GeoArmorItem
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:57) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:170) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at io.github.how_bout_no.outvoted.init.ModItems.<clinit>(ModItems.java:29) ~[outvoted-2.0.0-alpha.13-fabric.jar:?]
        at io.github.how_bout_no.outvoted.Outvoted.init(Outvoted.java:56) ~[outvoted-2.0.0-alpha.13-fabric.jar:?]
        at io.github.how_bout_no.outvoted.OutvotedFabric.onInitialize(OutvotedFabric.java:18) ~[outvoted-2.0.0-alpha.13-fabric.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
        ... 17 more

```

**Version (please complete the following information):**
 - Minecraft Version 1.17.1
 - Modloader Fabric
 - Mod Version Alpha 13

**Comment by elbakramer** [comment]
I think [this](https://github.com/bernie-g/geckolib/commit/50bea3996cf3d176202701164d6f3b0a5291bb58) commit broke the dependency. And by seeing [this](https://github.com/bernie-g/geckolib/commit/50bea3996cf3d176202701164d6f3b0a5291bb58#diff-01fba5ea74ce0bbd58eb0368ab3b34f187144782947d7150fbe6d3e4ed530958R24) example, it seems that we can just replace the previous `software.bernie.geckolib3.item.GeoArmorItem` to `net.minecraft.item.ArmorItem` in [here](https://github.com/How-Bout-No/Outvoted/blob/c6bcb576a6996eeb185c72546dcf46cb0684a38b/common/src/main/java/io/github/how_bout_no/outvoted/item/WildfireHelmetItem.java#L32), maybe?

**Comment by How-Bout-No** [comment]
> I think [this](https://github.com/bernie-g/geckolib/commit/50bea3996cf3d176202701164d6f3b0a5291bb58) commit broke the dependency. And by seeing [this](https://github.com/bernie-g/geckolib/commit/50bea3996cf3d176202701164d6f3b0a5291bb58#diff-01fba5ea74ce0bbd58eb0368ab3b34f187144782947d7150fbe6d3e4ed530958R24) example, it seems that we can just replace the previous `software.bernie.geckolib3.item.GeoArmorItem` to `net.minecraft.item.ArmorItem` in [here](https://github.com/How-Bout-No/Outvoted/blob/c6bcb576a6996eeb185c72546dcf46cb0684a38b/common/src/main/java/io/github/how_bout_no/outvoted/item/WildfireHelmetItem.java#L32), maybe?

A quick glance shows the latest GeckoLib fixed armor rendering and if I had to guess they probably switched up the classes. Changing the class to the vanilla one won't work because it requires the use of GeckoLib rendering. I'll see what I need to change it to.

**Comment by How-Bout-No** [comment]
Should be fixed in alpha 14
